sudo: false
language:
  - python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
install:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
script:
  - pycodestyle mamba_client
  - pytest --cov-config=.coveragerc --cov=mamba_client --verbose --capture=no tests
  - pip install .
after_success:
  - codecov
notifications:
  email: false
cache:
  directories:
  - "$HOME/.cache/pip"
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: cWqo32mRj8vY0XkuBLqoYjDfAUd+Deb4cskYBn5m8RHWBNyx8kZqNzObu7PxRF7jCF+D0WAIwkEDMaB21hyyc2+7CTbqoZuPbZk76GCKwuHU8TACAeg5y2UnUK8nDXRwWCfOyPQv7qNua52q8DIoetV5+zvUGYDGiItq1DPLXOclTpYLRaU1gAsAyIvUimTkXq6pfJYdiBgDbgg+8ICt0WLmSuCx07ywJZ5wMrZMenCoVwVdHvlDkUk1+iIMx30RQz9nkZKKpvFofM/SDeJsr0fvdv1xSqMqATF05pbj2JSO62Sc1/GWV73XnnR+NANlw7bxzFzMDd1gt53eLaEPPZnPhOsts3IuJRe9aU8axIjfh+0Rrs2Pr3jGChwp0lP8x9OPCwTnv1I3uJ3yFTaAc5K3/5P8CKI1v2T3KvAQIQwYyngenWm050LpnNsF0eDvJvV6MiDq+PeNMHoY/VjsdKvzmcgH8A2uKSU1vg6xKd4FCOmkq4blQftagFsfqXjv4A+spdYrO13CaROqBSmAqmQZ+OcSVxlTHfJ4advi65DrYSueeCIe7qUXf90dPv3xV81j+rY88/T/e4Q8W087BKUbav6e6ksHRk5JCNgltpM2Y2Hd1EDnktGgF8ZlfIwpBOt7ln86Xaz5tXfer0qNUHTCCF3+OoAM84fAP+mQ+I8=
  on:
    tags: true
    repo: mamba-framework/mamba-client
